CREATE TABLE "desktop-computer"
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type            INT,
    "serial-number" BIGINT                                  NOT NULL,
    fabricator      VARCHAR(255)                            NOT NULL,
    price           DOUBLE PRECISION                        NOT NULL,
    count           INT                                     NOT NULL,
    "form-factor"   VARCHAR(25)                             NOT NULL,
    CONSTRAINT "pk_desktop-computer" PRIMARY KEY (id)
);

ALTER TABLE "desktop-computer"
    ADD CONSTRAINT "uc_desktop-computer_serial-number" UNIQUE ("serial-number");

CREATE TABLE "hard-disk"
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type            INT,
    "serial-number" BIGINT                                  NOT NULL,
    fabricator      VARCHAR(255)                            NOT NULL,
    price           DOUBLE PRECISION                        NOT NULL,
    count           INT                                     NOT NULL,
    volume          INT                                     NOT NULL,
    CONSTRAINT "pk_hard-disk" PRIMARY KEY (id)
);

ALTER TABLE "hard-disk"
    ADD CONSTRAINT "uc_hard-disk_serial-number" UNIQUE ("serial-number");

CREATE TABLE laptop
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type            INT,
    "serial-number" BIGINT                                  NOT NULL,
    fabricator      VARCHAR(255)                            NOT NULL,
    price           DOUBLE PRECISION                        NOT NULL,
    count           INT                                     NOT NULL,
    size            VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_laptop PRIMARY KEY (id)
);

ALTER TABLE laptop
    ADD CONSTRAINT "uc_laptop_serial-number" UNIQUE ("serial-number");

CREATE TABLE screen
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type            INT,
    "serial-number" BIGINT                                  NOT NULL,
    fabricator      VARCHAR(255)                            NOT NULL,
    price           DOUBLE PRECISION                        NOT NULL,
    count           INT                                     NOT NULL,
    diagonal        INT                                     NOT NULL,
    CONSTRAINT pk_screen PRIMARY KEY (id)
);

ALTER TABLE screen
    ADD CONSTRAINT "uc_screen_serial-number" UNIQUE ("serial-number");